---
title: "ReporteT01"
author: "Jessica Garcia, Manuel Rivera, Axel Rodriguez"
date: "2023-02-10"
output:
  html_document:
    toc: true # table of content true
    toc_float: yes
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
  pdf_document: 
    toc: true
    toc_depth: 3
    number_sections: true
---

# Practica archivo BAM

```bash
# Entrar a un qlogin
qlogin
# Entrar a la carpeta donde se encuentra el archivp
cd /mnt/Timina/bioinfoII/format_qc
# Copiar el archivo a la carpeta donde se estará trabajando
cp NA20538.bam /mnt/Timina/bioinfoII/arodriguez
# Dirigirse a la carpeta donde se trabaja
cd /mnt/Timina/bioinfoII/arodriguez
# Cargar Samtools versión 1.9
module load samtools/1.9
# Visualizar información del BAM
samtools view –H NA20538.bam 
```

## ¿Qué significan las siglas RG? 

RG: _read group_, lecturas de grupo que se generan a partir de una única ejecución de un secuenciador. 

## ¿Qué es "lane ID"?

Identificador del grupo de lectura, esta etiqueta identifica a qué grupo de lectura pertenece cada lectura, por lo que el ID de cada grupo de lectura debe ser único.

## ¿Cuál es la plataforma de secuenciación?

Para conocer la plataforma utilizada, existe la etiqueta PL (*platform)*, que se puede encontrar en el encabezado del archivo BAM.

```bash
# Buscamos la etiqueta PL dentro del header
samtools view -H NA20538.bam | grep 'PL'
```

Para estas muestras se utiizo __Illumina__.

## ¿Qué versión de ensamblaje humano se usó para realizar las alineaciones?

Las entradas @SQ del encabezado contienen información acerca de las secuencias de referencia. La etiqueta AS (*genome assembly identifier*) nos habla acerca del genoma de referencia utilizado para realizar el alineamiento.

```bash
samtools view -H NA20538.bam | grep 'AS'
```

el genoma de ensamblaje utilizado fue el __NCBI37: GRCh37 (*Genome Reference Consortium Human Build 37*)__, especificamente el descargado del Proyecto de los 1000 genomas.

## ¿Qué programadas fueron utlizados para crear este archivo BAM?

La entrada @PG (*program*) del encabezado contiene la informacion de los programas utilizados. 

```bash
samtools view -H NA20538.bam | grep 'PG'| less -S
```

Los programas utilizados fueron:

- Genome Analysis Toolkit (GATK) IndelRealigner (version 1.0.4487)
- Genome Analysis Toolkit (GATK) TableRecalibration (version 1.0.4487)
- Burrows-Wheeler Aligner (bwa) (version 0.5.5)


## ¿Qué versión de bwa fue usada para alinear las lecturas?

VN _program version_, versión del programa: 0.5.5

```bash
#Observar información particular del BAM para responder las siguientes preguntas
samtools view NA20538.bam | head
```

## ¿Cuál es el nombre de la primera lectura?
ERR003814.1408899

## ¿En qué posición inicia el alineamiento de la lectura?
19999970

## ¿Cuál es la calidad de la primera lectura? 
23

# Practica archivo bfc

## ¿Que es un BCF?

Un BCF es el archivo binario del VCF.

##  ¿Como convertir un BCF-->VCF?

Si es posible convertir un bcf a vcf utilizando el comando $view$

```bash
#Convertir un BCG --> VCF
bcftools view 1kg.bcf -o 1kg.vcf
```

## ¿Cuantas muestras hay en el BCF?

Hay 50 muestras en total.

```bash

# Muestra los nombres de las muestras
bcftools query -l 1kg.vcf

# Muestra el numero de muestras con un pípeline
bcftools query -l 1kg.bcf | wc -l
```

## ¿Cual es el genotipo de la muestra HG00107 en la posicion 20:24019472?

```bash

#Comprimir VCF --> GZIP
bcftools view 1kg.vcf -Oz -o 1kg.vcf.gz

#Filtrar por nombre de la muestra
bcftools view -s HG00107 1kg.vcf.gz
 
#INDEX
bcftools index 1kg.vcf.gz

#Filtrar por posicion de la muestra y nombre
bcftools view -r 20:24019472 -s HG00107 1kg.vcf.gz

#Mostrar el genotipo
bcftools view -r 20:24019472 -s HG00107 1kg.vcf.gz | bcftools query -f '[ %TGT]\n' 
```


## ¿Cuantas posiciones tienen mas de 10 alelos diferentes?

```bash
# Saber posiciones
bcftools view -i 'AC>10' 1kg.vcf| wc -l

```


## Lista todas las posiciones en las que HG00107 no tiene un genotipo de referencia y la cobertura es mayor a 10.

```bash

# Mostrar la cobertura
bcftools query -f '[ % DP]\n'

# Filtrar por nombre
bcftools view -s HG00107 1kg.vcf

# Filtrar por no tener genoma de referencia
bcftools view -i 'GT="alt"' 1kg.vcf

# Ambos filtros
bcftools view -s HG00107 -i ' GT="." && DP>10' 1kg.vcf | wc -l #DUDA
bcftools view -s HG00107 -i ' REF="." && DP>10' 1kg.vcf | wc -l #DUDA

#Contar las posiciones
bcftools view -s HG00107 -i ' REF="." && DP>10' 1kg.vcf | wc -l #DUDA

#PRUEBA
bcftools view -r 20:29908139 -s HG00107 1kg.vcf.gz 
29908139
```

# Practicas estadisticas

## ¿Cual es numero total de lecturas?
Usando el comando `samtools flagstat` se puede observar las estadisticas generales del archivo BAM. Si lo que se requiere saber es el **numero total de lecturas**, entonces se utiliza el comando:

```bash
samtools flagstat NA20538.bam | head -n 1
```

En donde el comando `head -n 1` funciona para imprimir solo la primera linea del output, donde se encuentran el numero de lecturas totales.

```bash
347367 + 0 in total (QC-passed reads + QC-failed reads)
```

Como se observa, el numero de lecturas totales fue de **347,367**.

### Otras alternativas

```bash
# Estadisticas generales
samtools flagstat NA20538.bam
# Lecturas totales ejemplo 2
samtools view -c NA20538.bam # 347367
# Lecturas totales ejemplo 3
samtools stats NA20538.bam | grep 'SN' | cut -f 2- # 347367
# Lecturas totales ejemplo 4
samtools stats NA20538.bam | grep 'raw total sequences' | cut -f 2- # 347367
```

- `view -c` cuenta los alineamientos e imprime el total.
- `samtools stats` muestra estadísticas relevantes sobre cada lane y grupo de lectura, así como información sobre las secuencias.
- `grep` busca e imprime las lineas coincidentes con un patron (en el ej.3 `‘SN’`)
- La seccin `SN`  del comando `samtools stats` brinda un resumen con conteos, porcentajes y promedios, en un estilo similar al de `samtools flagstat`, pero más completo.
- `cut` se utiliza para seleccionar una columna del output. Con el parametro `-f 2-` le indicamos que solo queremos las ultimas dos columnas del output.
- `grep 'raw total sequences'` se utiliza para especificar que solo se requieren el total de lecturas, lo que nos da un output mas ordenado.

## ¿Que proorcion de las lecturas fueron mapeadas?

Con el mismo comando de `samtools flagstat NA20538.bam`, se observa que el porcentaje de _reads_ mapeados fue de **93.26%** (323,966 lecturas). 

```bash
# Filtramos los resultados que coincidan con 'mapped' e imprimimos
# todos los argumentos de la primera fila
samtools flagstat NA20538.bam | grep 'mapped'| awk '{print $0}'| head -n 1
323966 + 0 mapped (93.26% : N/A)
```

El comando `awk '{print $0}'` imprimir la primera fila del output del comando `samtools flagstat NA20538.bam | grep 'mapped'`.

<div class="alert alert-block alert-info">
Generalmente `awk '{print $n}'` es utilizado para imprimir la $n$-esima columna de un output. `awk ‘NR==m {print $n}’` se utiliza para imprimir la $m$-esima fila y la $n$-esima columna.</div>


### Otras alternativas

```bash
# Lecturas mapeadas (Mapped alignments)

## Ejemplo 2
samtools view -F 0x904 -c NA20538.bam # 323966
## Ejemplo 3
samtools view -c -F 260 NA20538.bam # # 323966
## Ejemplo 4
samtools view -F 0x04 -c NA20538.bam # 323966
## Ejemplo 5
samtools stats NA20538.bam | grep 'SN' | grep 'reads mapped' | cut -f 2- #323966
```

## ¿Cuantas lecturas fueron mapeadas a un cromosoma diferente?

```bash
samtools stats NA20538.bam | grep 'pairs on different chromosomes:' | cut -f 2-
```

De acuerdo a la seccion `SN` del archivo, **4,055** lecturas fueron mapeadas a un cromosoma diferente.

## ¿Cual es el tamaño de inserción promedio y su desviación estándar?

```bash
samtools stats -F SECONDARY NA20538.bam | grep "insert size" | cut -f 2-
```

Finalmente, en la seccion de _Sumary Numbers_ (`SN`) generada por `samtools stats` se encuentra la información requerida.

- tamaño promedio de inserción: **190.3**
- desviación estándar del tamaño de inserción: **136.4**




# Referencias
1. Copiar en Linux: con CP es muy sencillo. (s/f). IONOS Digital Guide. Recuperado el 20 de febrero de 2023, de https://www.ionos.mx/digitalguide/servidores/configuracion/comando-cp-de-linux/

2. Markdown: introducción al lenguaje de marcado. (s/f). IONOS Digital Guide. Recuperado el 20 de febrero de 2023, de https://www.ionos.es/digitalguide/paginas-web/desarrollo-web/tutorial-de-markdown/

3. The SAM/BAM Format Specification Working Group. (s/f). Sequence alignment/map format specification. Github.io. Recuperado el 20 de febrero de 2023, de https://samtools.github.io/hts-specs/SAMv1.pdf

4. Anónimo. (s/f). VCF AND BCF. Evolution and Genomics. Recuperado el 20 de febrero de 2023, de  https://evomics.org/vcf-and-bcf/#:~:text=BCF%2C%20or%20the%20binary%20variant,that%20between%20BAM%20and%20SAM.



